### ISSUE TITLE
트랜슬레이션(Translation) -> 트랜지션(Transitions)

### ISSUE THREAD

**Issue by taegon** [HyunSeob/solved-by-flexbox-kr#1]
우선 번역을 해주셔서 손쉽게 읽을 수 있었습니다. 이점 감사드립니다.
서론 부분에서 첫 문단에 단어가 잘못 들어가서 알려드립니다.

그리고 몇가지 제안을 하자면, "서론"은 "들어가기", "시작하기", "소개" 정도 바꿔쓸 수 있을 것 같습니다.

"이 사이트는 CSS 프레임워크가 아닙니다."는 조금만 풀어 써서, "이 사이트는 또 다른 CSS 프레임워크를 소개하는 것이 아닙니다." 정도로 번역하면 어떨까 싶네요. CSS 프레임워크가 범람하는 시대에 또다른(새로운) 프레임워크를 보태는 것이 아니라, 브라우저의 기본기능으로 내장된 Flexbox를 활용하는 방법을 소개하고 있기 때문입니다.

**Comment by HyunSeob** [comment]
#2 에서 해결되어 close 하겠습니다 🙏
